# Generated by Django 4.1.1 on 2022-11-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='brand',
            field=models.CharField(max_length=255),
        ),
    ]
